name: Deploy React App to S3 (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend   # ✅ frontend 디렉토리 명시

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
     

      - name: Ensure package-lock.json exists
        run: test -f package-lock.json || (echo "❌ package-lock.json not found!" && exit 1)

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Deploy React build to S3 (build/ only)
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete --cache-control "no-store"
        env:
          AWS_S3_BUCKET: image-resolution-output-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build
