name: Create IAM Role (IAMUSER only)

on:
  workflow_dispatch:

jobs:
  deploy-iam-role:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAMROLE_CREATE }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAMROLE_SECRET }}
      AWS_REGION: ap-northeast-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: IAMUSER
        run: terraform init

      - name: Terraform Apply (IAMUSER only)
        working-directory: IAMUSER
        run: |
          terraform apply -auto-approve \
